In [114]:
!python rnn_name_generator.py


66
[[36 23 16 ...  0  0  0]
 [46 11  5 ...  0  0  0]
 [31 20  7 ... 16  2  0]
 ...
 [37 16  6 ...  0  0  0]
 [29 15 11 ...  0  0  0]
 [41  3 20 ...  0  0  0]]
[[ 1. 36. 23. ...  0.  0.  0.]
 [ 1. 46. 11. ...  0.  0.  0.]
 [ 1. 31. 20. ...  7. 16.  2.]
 ...
 [ 1. 37. 16. ...  0.  0.  0.]
 [ 1. 29. 15. ...  0.  0.  0.]
 [ 1. 41.  3. ...  0.  0.  0.]]
tensor([[ 1, 36, 23,  ...,  0,  0,  0],
        [ 1, 46, 11,  ...,  0,  0,  0],
        [ 1, 31, 20,  ...,  7, 16,  2],
        ...,
        [ 1, 31,  3,  ...,  0,  0,  0],
        [ 1, 32,  7,  ...,  0,  0,  0],
        [ 1, 32,  3,  ...,  0,  0,  0]])
Num_batches:  2352
Epoch:   0
0.06535259469605537
The value is 2.841433380970501
Epoch:   1
0.05495612727227511
The value is 2.667997771833561
Epoch:   2
0.052850056931499814
The value is 2.5919730474290863
Epoch:   3
0.051325652332799
The value is 2.5076441804305927
Epoch:   4
0.049948888677558506
The value is 2.4604515526895856
Epoch:   5
0.04920211669579786
The value is 2.437132991813787
E

In [30]:
import numpy as np
np.zeros([1,2,3

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [31]:
import torch
torch.zeros([1,32,32])

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])

In [57]:
import numpy as np
a = np.array([3, 1, 2, 4, 6, 1])
print(np.argmax(a))

4


In [62]:
a = [[[-0.07161187 -0.11109842 -1.7526138  -0.5400143  -0.73267436
   -0.6357001  -1.4770299  -0.46955565 -1.0050548  -1.1705222
    0.07628696 -0.3619486  -0.56811327 -0.9749072  -1.3590527
   -1.2157094  -1.5867379  -0.43071085 -0.5932253  -0.43895257
   -0.85148203 -1.460752   -1.3554217   0.09032555 -0.97215414
   -0.82321817 -0.83840424 -1.1693616  -1.1320436   1.9130158
    2.1415708   2.1308305   2.6425164   2.035138    1.5930427
    2.1524332   2.0918796   1.376087    2.6151671   1.9872931
    1.9861645   2.5394511   1.5876548   1.1803627   2.0103061
    0.5083054   2.2615132   2.1122117   2.1338174   0.7289499
    1.2193878   1.6895767   0.06026842  0.9418176   0.7347265
   -0.80517757 -0.10561883 -0.28539437 -0.4224071  -0.15557887
   -0.2281552  -0.0431152  -0.20877093 -0.11114657 -0.44710365
   -1.761656  ]]]
a[1][1][32]

SyntaxError: invalid syntax (2414127897.py, line 3)

In [74]:
x = torch.ones((1, 1), dtype=torch.long)
tx = torch.full((1,1), 41, dtype=torch.long)
print(x)
print(tx)

tensor([[1]])
tensor([[41]])


In [87]:
from numpy.random import choice
draw = choice([1,2,3,4], 1,
              p=[0.1, 0.1, 0.1, 0.7])
for i in range(10):
    draw = choice([1,2,3,4], 1,
              p=[0.10, 0.01, 0.01, 0.88])
    print(draw[0])

4
4
4
4
4
4
1
4
4
4


In [102]:
import string
def get_vocab():
    # Construct the character 'vocabulary'
    # we allow lowercase, uppercase and digits only, along with special characters:
    # "" - Empty string used to denote elements for the RNN to ignore
    # "<bos>" - Beginning of sequence token for the input the the RNN
    # "." - End of sequence token
    vocab = ["", "<bos>", "."] + list(string.ascii_lowercase + string.ascii_uppercase + string.digits + " ")
    id_to_char = {i: v for i, v in enumerate(vocab)} # maps from ids to characters
    char_to_id = {v: i for i, v in enumerate(vocab)} # maps from characters to ids
    return vocab, id_to_char, char_to_id

a,b,c = get_vocab()
len(a)
a = list(range(0,66))
print(a)
b[65]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65]


' '

In [ ]:
Argmax:  John Berner
Random:
Corry Rodsman
Adson Toomes
Kristin Morcher
Ton Svades
Marret Ruvacki
Davita Allewy
Kun Kasel
Velan Marven
Chilb Pazlder
L M Maloto